### ISSUE TITLE
Feature: Allow changing the turret voices.

### ISSUE THREAD

**Issue by KaziPlays** [ChaosInitiative/Portal-2-Community-Edition#692] opened 2021-08-18 17:41 UTC
### Which component should be improved?

Entity

### Describe your suggestion

PS:M's 50s turrets were going to have a custom voice, this would allow this to be possible.

### Expected result

I don't know how the user would change the Voice without overwriting it. Probably a menu of sorts.

You click the menu and there's a list of voicelines the turret speaks.

**Comment by Luke18033** [comment] 2021-08-18 17:50
Duplicate of #373. GitHub has a really cool feature called "search", you should try it out.

**Closed by Luke18033** 2021-08-18 17:50 UTC
Labels: type/enhancement
