### ISSUE TITLE
Add 'IES Lighting'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#300] opened 2020-08-04 18:24 UTC
![image](https://user-images.githubusercontent.com/26350889/89330428-200f6e80-d688-11ea-8d68-3a1a50aa91ae.png)

**Comment by distributivgesetz** [comment] 2020-08-04 19:23
Duplicate of #29, please search up issues before spamming issues from the webpage, thanks.

**Comment by AddMGH** [comment] 2020-08-04 19:24
> 
> 
> Duplicate of #29, please search up issues before spamming issues from the webpage, thanks.

I searched 'lighting', not 'ies'.

**Closed by distributivgesetz** 2020-08-04 19:23 UTC
