### ISSUE TITLE
Water screen overlay appears on respawn after death in water

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#423] opened 2020-10-19 08:51 UTC
If you die in water and respawn, a water overlay animation appears on screen.

This issue exists in csgo as well

**Comment by Luke18033** [comment] 2020-10-19 16:45
Duplicate of #183 (in which I stated in a comment that the bug was still present, and was ignored)

**Comment by CitadelCore** [comment] 2020-10-19 19:46
This is fixed for good now. Cvars have been un-marked as cheat.

**Closed by CitadelCore** 2020-10-19 19:46 UTC
Labels: render, type/bug
