### ISSUE TITLE
Bug: Custom Webm Backgrounds With Audio Do Not Work

### ISSUE THREAD

**Issue by koerismo** [ChaosInitiative/Portal-2-Community-Edition#532] opened 2021-03-04 04:31 UTC
### Describe the bug
Some custom webm backgrounds do not function and are replaced with the default static image. This appears to happen when the video contains audio.

### To Reproduce
1. Create video with audio
2. Use FFMPEG to convert to webm
3. Insert webm as main menu background into mod files
4. Launch mod and wait for main menu to appear

### Expected behavior
A static variant of the default chapter background will appear instead of the supplied video.

### Operating System (Optional: Only if OS Specific)
Windows 10

**Comment by Joshua-Ashton** [comment] 2021-03-04 04:52
99.9% you are using the wrong codec in ffmpeg. Webm is just a container.

**Comment by SpyceTewan** [comment] 2021-03-04 07:19
yeah we only support a couple of codecs. would be good to know which one you tried to use

**Comment by koerismo** [comment] 2021-03-04 12:54
According to VLC Media Player:
![image](https://user-images.githubusercontent.com/56563658/109966849-b6f3e600-7cbe-11eb-845c-722217038c70.png)

**Comment by koerismo** [comment] 2021-03-04 14:03
Fixed on my end, but this is still an issue.

**Comment by JJL772** [comment] 2021-11-19 16:31
Closing this as we only support vorbis for now, so this is not a bug. Feel free to open another issue if you want us to support more codecs, it's not really on our radar right now.

**Closed by JJL772** 2021-11-19 16:31 UTC
Labels: type/bug, can't reproduce
