### ISSUE TITLE
Fix static effect of projected textures in NVIDIA drivers

### ISSUE THREAD

**Issue by BlightedLight** [ChaosInitiative/Portal-2-Community-Edition#28] opened 2019-02-21 11:31 UTC
Fix static/grain effect that happens on surfaces with nVidia graphics cards. (Only happens with projected textures...?)

![image](https://user-images.githubusercontent.com/35391144/53165453-79afe480-361e-11e9-9c30-b7e8eb919a86.png)

**Comment by CitadelCore** [comment] 2019-02-22 18:04
Is this already fixed in the CS:GO branch?

**Comment by ethan101au** [comment] 2019-02-23 00:44
I've never seen this happen in CSGO, so I would assume so.

**Comment by Luke18033** [comment] 2019-02-26 21:34
Specifically, the issue is caused by a combination of projected textures, `$detailblendmode 0` and bumpmaps. It doesn't exist in any other games as far as I know.

**Comment by SpyceTewan** [comment] 2020-08-15 21:15
Yes this is fixed in csgo

**Closed by SpyceTewan** 2020-08-15 21:15 UTC
Labels: bug

**Comment by FrozenDragon0** [comment] 2020-08-16 00:42
Sad to see how valve hasn't even fixed this annoying bug in default P2, don't even give 2 shits about it.

**Comment by warmCabin** [comment] 2021-02-08 06:53
How was this fixed? Can it be applied to vanilla Portal 2?

**Comment by FrozenDragon0** [comment] 2021-02-08 07:03
@warmCabin It's because P2:CE is on the CS:GO engine which doesn't have this problem. Don't expect a fix for portal 2 as this has been known for years and valve or Nvidia has done nothing about it.

**Comment by warmCabin** [comment] 2021-02-08 07:25
I'm all too familiar with the annoying history of this issue :(
But I was wondering if you knew what they actually did to fix it between P2 and CS:GO, and if there could be some kind of community patch/mod/janky workaround.

**Comment by CitadelCore** [comment] 2021-02-08 08:21
This isn't relevent to P2CE, please continue discussion elsewhere
