### ISSUE TITLE
Add func_paint_detector

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#277] opened 2020-07-28 22:38 UTC
Pretty much what the title says. Be able to detect paint in a determinated area. (I don't know if it's possible to do)

**Comment by SpyceTewan** [comment] 2020-07-28 22:39
Duplicate of #42

**Closed by SpyceTewan** 2020-07-28 22:39 UTC
Labels: duplicate

**Comment by L89David** [comment] 2020-07-28 22:41
This is actually a different thing though. Not gel flow.
I meant detecting gel that has been applied to a surface.

**Comment by Luke18033** [comment] 2020-07-28 22:46
That would be a duplicate of #43 then.
