### ISSUE TITLE
Bug: HL2 weapons worldmodel render at player's feet

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#922] opened 2022-06-20 02:48 UTC
### Describe the bug

While holding a HL2 weapon, you can see the worldmodel at that player's origin point
![20220619214501_1](https://user-images.githubusercontent.com/16567080/174516350-28865a1c-7a2f-47b9-ac27-e0d8c517a1c4.jpg)

### Issue Map

All maps

### To Reproduce

Give yourself a half life 2 weapon and look down

**Comment by Luke18033** [comment] 2022-06-20 02:49
Duplicate of #522

**Closed by Luke18033** 2022-06-20 02:49 UTC
Labels: Type: bug
