### ISSUE TITLE
Bug: Func_reflective_glass does not work properly in P2CE

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#848] opened 2022-04-04 04:35 UTC
### Describe the bug

func_reflective_glass is a brush entity that reflects the world around it. In P2 and P2CE it doesn't work properly.

### To Reproduce

create a map with one, walk around and see how it's broken.

**Comment by Luke18033** [comment] 2022-04-04 04:36
Duplicate of #280

**Closed by Luke18033** 2022-04-04 04:36 UTC
Labels: Type: bug
