### ISSUE TITLE
Fix projected texture NVIDIA driver graphics bug

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#128] opened 2020-06-24 11:28 UTC
Fix this bug: https://www.youtube.com/watch?v=PJ1mnJHln5Q

**Comment by distributivgesetz** [comment] 2020-06-24 11:29
Wait, there is no issue on this already?

**Comment by distributivgesetz** [comment] 2020-06-24 11:30
There is, duplicate of #28

**Closed** 2020-06-24 11:33 UTC
Labels: bug, duplicate, render
