### ISSUE TITLE
Custom Loading Screen Background Images

### ISSUE THREAD

**Issue by MrGermandeutsch** [ChaosInitiative/Portal-2-Community-Edition#363] opened 2020-09-10 13:03 UTC
We've all seen the standart loading screen background-images in Portal 2 and various other custom loading screen background-images of Portal 2 related Mods.
But I highly believe that it would be a lovely addition to have the ability to add custom loading screen background-images to our maps (when starting the map or loading from a savepoint).
It may not affect the gameplay itself, but it would be a neat aesthetic addition to the community edition, if possible of course.

I would be greatly interested as to what kind of backgrounds I would get to see if people were able to add their own images during loading times-
Maybe some interesting artwork, perhaps some neat hints, maybe even just plain ol' memes, who knows :^)

![Compressed2_Portal_2_Community_Edition_-_Suggestion_-_Custom_Loading_Screen_-_by_MrGermandeutsch](https://user-images.githubusercontent.com/40644932/92732365-a4839a00-f376-11ea-91ac-821383f1bb64.gif)

**Comment by distributivgesetz** [comment] 2020-09-10 13:12
Probably duplicate of #44

**Comment by ozxybox** [comment] 2022-06-28 03:37
Superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/928.

**Closed by ozxybox** 2022-06-28 03:37 UTC
Labels: Type: enhancement
