### ISSUE TITLE
Prop_mirror / Func_reflective_glass fix

### ISSUE THREAD

**Issue by CamBen** [ChaosInitiative/Portal-2-Community-Edition#403] opened 2020-09-26 22:43 UTC
Either make Func_reflective_glass render the player, or make Prop_mirror properly render the world without props flashing in and out.

Fix whichever one used not to cause crashing issue with portals.

**Comment by CitadelCore** [comment] 2020-09-27 00:32
Duplicate of #280

**Closed by CitadelCore** 2020-09-27 00:32 UTC
Labels: duplicate
