### ISSUE TITLE
Bug: game crashes when loading new map on Linux

### ISSUE THREAD

**Issue by Paladiumer** [ChaosInitiative/Portal-2-Community-Edition#478] opened 2020-12-13 14:58 UTC
The bug: I start any chapter, I finish the 1st map and when loading the next level the game crashes
### To Reproduce
1. Open map
2. Finish the test
3. Game crashes when loading the next map

### Expected behavior
The game should load the map normally and let the player continue 

### Operating System (Optional: Only if OS Specific)
 - OS: Ubuntu (20.04 and newer in my case

Computer specs (who knows, it might be helpful):
MacBook Pro 15inch 2015; Intel Core I7 4980HQ 2.8GHz, 16GB 1600MHz RAM; AMD R9 M370X 2GB

**Comment by JJL772** [comment] 2020-12-13 15:00
Have you tried running the game with the steam linux runtime? This can be done in the properties UI in steam.

**Comment by Paladiumer** [comment] 2020-12-13 15:03
I'll try that when I'll be able to

**Comment by JJL772** [comment] 2020-12-13 15:04
Thanks. This is a new bug, none of the other Linux testers have reported anything like this.

**Comment by SpyceTewan** [comment] 2020-12-29 17:00
I can't reproduce this. Loading maps works fine for me

(Kubuntu 20:10)

**Comment by Paladiumer** [comment] 2020-12-29 17:03
I guess it's an issue specific to my hardware (again, I don't know why this happens, the 1st time the game worked fine and then it started crashing again)

**Comment by JJL772** [comment] 2020-12-30 01:45
Just to confirm, does running it in the steam linux runtime not fix the problem? 

It could be a problem with your GPU. The specs in this post are up to date right?

**Comment by JJL772** [comment] 2021-01-03 23:29
I've confirmed this with the steam build of the game. Never had it before until now, so I'm not sure what happened.

**Comment by Paladiumer** [comment] 2021-01-04 16:33
Well maybe next time I'll have to precise which build is it to help a bit, but it's pretty surprising it also happened to you

**Comment by JJL772** [comment] 2021-01-04 22:26
This doesn't happen with our current internal build, so I'm not sure what went wrong with the steam deployment. 
I'm not going to mark this as resolved until the next release on steam, just in case this is an issue with something in the deployment process.

**Comment by JJL772** [comment] 2021-05-27 13:51
Apparently this crash disappeared for him with 0.5.7's release. So I'm just going to close this

**Closed by JJL772** 2021-05-27 13:51 UTC
Labels: can't reproduce, crash, posix specific, type/bug
