### ISSUE TITLE
move_rope entities crash hammer

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#238] opened 2020-07-16 20:14 UTC
move_rope entities have an error texture on them and also randomly blow up to massive sizes, especially when looking straight up or straight down in the hammer 3d viewport.

**Comment by distributivgesetz** [comment] 2020-07-17 09:40
What about a crash, as suggested in the title?

**Comment by Konclan** [comment] 2020-07-17 22:13
What about it? move-rope entities will cause hammer to crash sometimes when looking straight up or down

**Comment by distributivgesetz** [comment] 2020-07-18 10:57
I can't reproduce this

**Comment by distributivgesetz** [comment] 2020-07-18 11:02
A couple seconds after saying that I can't reproduce it, it happens... amazing...
Apparently you have to stare at it straight down at a distance to make it blow up in size, and this affects seemingly every entity that has a missing texture, but most notably `move_rope` because it blows up the biggest and covers almost the entire viewport.

**Comment by JJL772** [comment] 2021-11-10 12:41
I'm not able to reproduce this. Can you confirm this is fixed in one of the recent p2ce builds?

**Comment by Luke18033** [comment] 2021-11-28 04:15
Can't reproduce, though the crash might just happen when the iconsprite is missing (the move_rope one no longer is)

**Comment by Luke18033** [comment] 2021-11-28 04:56
Should be fixed

**Closed by Luke18033** 2021-11-28 04:56 UTC
Labels: type/bug, render, component/tools, needs testing
