### ISSUE TITLE
Bug: Background video is darker than source webm

### ISSUE THREAD

**Issue by AWildErin** [ChaosInitiative/Portal-2-Community-Edition#1044] opened 2022-09-24 10:03 UTC
### Describe the bug

This may be a VGUI specific thing but im too lazy to test. The background video is darker compared to the original video file
![image](https://user-images.githubusercontent.com/28122025/192092125-5b3bbbe7-7444-4cd8-b99f-3271da7bfec4.png)
![image](https://user-images.githubusercontent.com/28122025/192092115-01cdfc3e-a32c-4d05-af56-f7916afa339b.png)

### Issue Map

N/A

### To Reproduce

1. Open P2CE
2. See the fact that the background video was darker than before

**Comment by pivotman319-owo** [comment] 2022-09-24 12:41
can't repro on my end, even on dx9 and pano mode

![VGUI Legacy, DX9/DX11](https://user-images.githubusercontent.com/15126754/192098491-45d06cb7-5101-4212-b077-2de6a93699f9.png)
![Panorama](https://user-images.githubusercontent.com/15126754/192098516-5bc31c69-659a-4578-ba07-291f8ca4d21b.png)

**Comment by AWildErin** [comment] 2022-09-25 01:41
Keep in mind at the time of this report I was on a developer build so I had changes that didn't hit live at the time

**Comment by JJL772** [comment] 2022-09-25 03:42
This should be in nightly by now. The issue is known and is because of gamma correction done to fix video brightness on in-game monitors. We just need to add a combo to disable gamma correction for videos played by video_services.

**Comment by pivotman319-owo** [comment] 2022-09-30 19:42
Fixed in nightly and staging

![chaos_2022-09-30_21-07-40](https://user-images.githubusercontent.com/15126754/193344806-dc98e2a2-3e83-41bc-8442-97a512116bae.png)

**Closed** 2022-09-30 19:43 UTC
Labels: Type: bug
