### ISSUE TITLE
Starting a map twice crashes the game with volumetric projected textures

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#377] opened 2020-09-13 15:20 UTC
If you are in a map with volumetric projected textures and load the map again or type restart, the game crashes

**Comment by BlightedLight** [comment] 2020-09-16 11:17
I doubt these issues are related, I'd keep testing.

**Comment by Luke18033** [comment] 2020-09-16 22:55
I also experienced a crash after the double-reload in Prototype's Adhesion maps. No idea if that's related, or if it would still happen in current builds.

**Comment by Luke18033** [comment] 2020-09-18 00:54
That crash does still happen.

**Comment by CitadelCore** [comment] 2020-10-20 06:55
Is this still an issue? I can't reproduce it.

**Comment by CitadelCore** [comment] 2020-11-13 12:40
Closing, if you can reproduce it directly please re-open.

**Closed by CitadelCore** 2020-11-13 12:40 UTC
Labels: crash, type/bug
