### ISSUE TITLE
Feature: Add an option to the tractor beam entity to allow it's model to be changed properly.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#669] opened 2021-07-25 01:04 UTC
## Which component should be improved?
prop_tractor_beam

## Describe your suggestion
What this feature would do is add an option to the prop_tractor_beam entity that allows it's model to be changed, you can do this in Portal 2 currently however, if you change the model of the tractor beam to something else it breaks the animations, preventing custom models from being used such as a dirty skin for overgrown or something. This is a problem in BEE2 in overgrown style as a custom model is unable to be used without having broken animations.

## Expected result
End result would be that the tractor beam's model would be changed whilst the animations still work properly rather than being broken.

**Comment by Luke18033** [comment] 2021-07-25 01:06
Duplicate of #130.

**Comment by FrozenDragon0** [comment] 2021-07-25 01:07
Ah, didn't even see that.

**Closed by Luke18033** 2021-07-25 01:06 UTC
Labels: type/enhancement
