### ISSUE TITLE
Map Transitions will Crash the Game

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#525] opened 2021-02-25 23:28 UTC
### Describe the bug:
When transitioning from one map to another in any means, the game will instantly crash.

### To Reproduce:
Any map will work, but:
1. Open sp_a1_intro2
2. Play the map and enter the elevator to transition to sp_a1_intro3
3. Observe as the game suddenly crashes.

### Expected behavior:
The map should transition to the next.

**Comment by SpyceTewan** [comment] 2021-03-02 23:51
I can't reproduce this

**Comment by JJL772** [comment] 2021-05-04 23:15
Apparently this happens due to the instances folder :trollface: (See #583)

**Comment by JJL772** [comment] 2021-05-27 13:02
This issue has been superseded by #583 (Not fixed as of 0.5.7)
I want to consolidate issues a bit more. All further discussion should take place on #583

**Closed by JJL772** 2021-05-27 13:02 UTC
Labels: type/bug
