### ISSUE TITLE
Purple Funnel

### ISSUE THREAD

**Issue by donsomeone** [ChaosInitiative/Portal-2-Community-Edition#164] opened 2020-07-09 19:22 UTC
Basically create an interaction between orange and blue tractor beam. Objects should freeze when interacting with the purple funnel.

**Comment by SpyceTewan** [comment] 2020-07-09 19:53
Duplicate of #55

**Closed** 2020-07-09 19:53 UTC
Labels: duplicate

**Comment by donsomeone** [comment] 2020-07-09 20:16
oh sorry
