### ISSUE TITLE
Bug: Turrets do not treat clips as solid

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#548] opened 2021-04-10 17:03 UTC
### Describe the bug
[Turrets do not treat clips as solid](https://youtu.be/IQPmFYo_1qw)

### To Reproduce
1. Load into turret intro
2. Check the first turret after entering the chamber.

### Expected behavior
This turret is not supposed to fall over through the clip
- [Regular Portal 2](https://i.imgur.com/666XRSH.jpg)
- [P2CE](https://i.imgur.com/7oR5tH4.jpg)

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by SpyceTewan** [comment] 2021-04-10 17:53
Duplicate of #228 but I'll keep this one as it has better description

**Comment by SpyceTewan** [comment] 2021-04-15 14:09
Fixed

**Closed by SpyceTewan** 2021-04-15 14:09 UTC
Labels: backwards compatibility, type/bug
