### ISSUE TITLE
Model appears to be invisible ingame when using material

### ISSUE THREAD

**Issue by koerismo** [ChaosInitiative/Portal-2-Community-Edition#417] opened 2020-10-15 23:04 UTC
My model properly renders in hammer, hlmv, and such, but not ingame.  It only stopped working properly after I updated the material to have `$envmap` and `$selfillum`. I have masks for both of these parameters.
Here is the vmt:
```
VertexLitGeneric
{
$basetexture "models/lunarcollab/[redacted]/[redacted]_diffuse_2"
$selfillum 1
$selfillummask "models/lunarcollab/[redacted]/[redacted]_emit_2"
$envmap env_cubemap
$envmapmask "models/lunarcollab/[redacted][redacted]_specular"
}
```

**Comment by SpyceTewan** [comment] 2020-10-15 23:08
So that we know it really is a materal and not a mesh issue, can you confirm that the model renders in wireframe?

**Comment by koerismo** [comment] 2020-10-15 23:14
It does not show the wireframe ingame, but it does in model viewer and etc. (Side note: physics and behaviour are normal other than appearance)

**Comment by SpyceTewan** [comment] 2020-10-16 05:50
Try r_flushlod

**Comment by Luke18033** [comment] 2020-10-16 16:27
That command has never worked for me, usually just crashes the game.

**Comment by Luke18033** [comment] 2020-10-17 02:42
Note that I have basically this same issue with my custom portal gun model - it renders fine in normal P2, but is completely invisible in P2CE. Have you tried recompiling the model under a different name? That's what "fixed" my problem. `r_flushlod` did not work, and indeed caused a crash as I mentioned earlier.

**Comment by koerismo** [comment] 2020-10-17 02:46
Update: I have recompiled the model, reviewed the materials, and compiled a map in regular p2. I recompiled the same map for p2ce. The model displays and acts normal in p2, but is still invisible in p2ce.

**Comment by SpyceTewan** [comment] 2020-12-11 16:13
Have you packed the model in a vpk and if so which vpk.exe did you use?

**Comment by koerismo** [comment] 2020-12-12 13:42
The model was not packed in a vpk.

**Comment by SpyceTewan** [comment] 2020-12-13 19:58
It would help a lot to have this model on hand to debug this

**Comment by koerismo** [comment] 2020-12-14 14:31
I sent EchoesForeAndAft the model and materials some time ago.

**Comment by CitadelCore** [comment] 2020-12-16 20:44
They're no longer part of our team, so please send them directly to one of us.

**Comment by SpyceTewan** [comment] 2021-01-06 15:13
Closing this. We don't have issues with invisible models and can't reproduce this without the model sources

**Closed by SpyceTewan** 2021-01-06 15:13 UTC
