### ISSUE TITLE
Bug: Crowbar kills zombies by slicing them in two and setting them on fire

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#712] opened 2021-09-11 07:09 UTC
### Describe the bug

I mean, the title kind of says it all, but when you kill a zombie with the crowbar they're sliced in two and set on fire.

### To Reproduce

1. Load any map and run `ent_create npc_zombie`
2. Run `give weapon_crowbar; use weapon_crowbar`
3. Kill zombie and observe death is rather irregular

### Expected Behavior

The zombie just dies like other NPCs.

### Operating System

Reported on Windows 10.

**Comment by JJL772** [comment] 2021-09-11 07:12
There's something wrong with the damage code. Seems like it's applying a ton of damage and the wrong damage type or something. Maybe mixed up bitflags?

**Comment by AWildErin** [comment] 2022-04-03 05:38
Both this and #572 have been fixed internally as they were caused by the same root issue. Leaving this open until the changes get pushed to Steam

**Closed** 2022-04-10 08:05 UTC
Labels: Type: bug, Status: needs testing, Focus: portal compat
