### ISSUE TITLE
Pause the game when opening console

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#369] opened 2020-09-11 19:25 UTC
When you open the console, the game pauses, but not entirely. The sounds keep playing for example.
It would be much easier to just pause the game completely when opening the console, just like how Portal 2 does it.

**Comment by SpyceTewan** [comment] 2020-09-11 19:26
Duplicate of #216. Will reopen that other ticket

**Closed by SpyceTewan** 2020-09-11 19:26 UTC
