### ISSUE TITLE
Bug: trigger_portal_cleanser occasionally crashing when interacting with NPCs

### ISSUE THREAD

**Issue by VirgilCore** [ChaosInitiative/Portal-2-Community-Edition#1110] opened 2023-01-13 20:09 UTC
### Describe the bug

When a trigger_portal_cleanser volume is set with the flag NPC enabled, and an NPC enters it, the model for the NPC will A-pose, float upward and dissapear, however on occasion the game will crash when the NPC is deleted.

### Issue Map

All

### To Reproduce

1. Create a trigger_portal_cleanser
2. Set spawnflag "NPCs" to true
3. Push a few npc_citizen into the trigger

**Comment by pivotman319-owo** [comment] 2023-01-13 21:44
possible duplicate of issue #975

**Closed** 2023-01-13 21:44 UTC
Labels: Type: bug
