### ISSUE TITLE
Add 'Physically Based Rendering shader'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#305] opened 2020-08-04 18:27 UTC
![image](https://user-images.githubusercontent.com/26350889/89330677-885e5000-d688-11ea-8c12-3f50b30dd701.png)

**Comment by distributivgesetz** [comment] 2020-08-04 19:24
Duplicate of #144, please search up issues before spamming issues from the webpage, thanks.

**Comment by AddMGH** [comment] 2020-08-04 19:25
yes, because i know what pbr is

**Closed by distributivgesetz** 2020-08-04 19:24 UTC
