### ISSUE TITLE
Bug: Mistextured walls in Portal 1 maps

### ISSUE THREAD

**Issue by Equalizer5118** [ChaosInitiative/Portal-2-Community-Edition#1126] opened 2023-01-29 01:47 UTC
### Describe the bug

Loading into any portal 1 map will show a few walls (most noticeably walls in the escape maps) that are mistextured

### Issue Map

Mainly escape_* maps, some walls will show with harsh orange fades going upwards

### To Reproduce

1. load into escape_00
2. get past the first section with the 5 pistons
3. look at the walls after the first dropdown

**Comment by TeamSpen210** [comment] 2023-01-29 01:53
A bunch of P1 resources were replaced with different ones in Portal 2, which is what causes this and #1125.

**Comment by AWildErin** [comment] 2023-01-29 09:15
Yeah this isn’t really an issue/bug. If portal 1 is mounted using cfg/mounts.kv and it still happens, please re-open it or make a new issue, but I’m gonna close this since it’s not a bug with p2ce at all.

**Closed by AWildErin** 2023-01-29 09:15 UTC
Labels: Type: bug
