### ISSUE TITLE
prop_laser_catcher doesn't become yellow after quicksave/quickload

### ISSUE THREAD

**Issue by LambdaCore21** [ChaosInitiative/Portal-2-Community-Edition#1054] opened 2022-10-02 17:01 UTC
### Describe the bug

prop_laser_catcher doesn't become yellow when powered.

Happens after quicksave/quickload.

![p_l_c](https://user-images.githubusercontent.com/63379443/193466492-b631e7c2-e145-496e-9c40-4c9b87cf26d1.png)

### Issue Map

sp_a2_triple_laser, sp_a2_ricochet, etc.

### To Reproduce

1. Load a P2 campaign map
2. Quicksave (F6)
3. Quickload (F7)
4. Trigger/power a prop_laser_catcher

### Operating System

Win10 64-bit

**Comment by pivotman319-owo** [comment] 2022-10-02 19:05
confirmed reproducible

https://user-images.githubusercontent.com/15126754/193471624-6652e108-2915-4afc-915d-e16976e095ce.mp4

**Comment by Luke18033** [comment] 2022-10-02 19:52
Duplicate of #184

**Closed by Luke18033** 2022-10-02 19:52 UTC
Labels: Type: bug, Component: entities, Component: gameplay, Compat: Portal 2, Priority 3: Medium, Size 4: Small

**Comment by AWildErin** [comment] 2022-10-02 19:54
I'd prefer this issue super seed #184 since this actually has reproducing steps
